services:
  llama-server:
    image: ghcr.io/ggml-org/llama.cpp:server-rocm
    container_name: llama-server
    restart: "no"

    devices:
      - /dev/kfd
      - /dev/dri

    security_opt:
      - seccomp=unconfined

    ipc: host

    ports:
      - "127.0.0.1:8080:8080"

    volumes:
      - ${MODELS_PATH}:/models:ro,Z
      - ./models.ini:/config/models.ini:ro,Z

    command:
      - --models-preset
      - /config/models.ini
      - --models-max
      - "1"
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --tools
      - all
